version: "3.9"
services:
  wrapper:
    build: .
    container_name: codex-wrapper
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      JWT_SECRET: ${JWT_SECRET:-changeme}
      REDIS_URL: redis://redis:${REDIS_PORT:-6379}
    ports:
      - "8123:8123"
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "${REDIS_EXTERNAL_PORT:-6379}:${REDIS_PORT:-6379}"